/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardBrainstormRouteImport } from './routes/board/brainstorm'

const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBrainstormRoute = BoardBrainstormRouteImport.update({
  id: '/brainstorm',
  path: '/brainstorm',
  getParentRoute: () => BoardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/board/brainstorm': typeof BoardBrainstormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/board/brainstorm': typeof BoardBrainstormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/board/brainstorm': typeof BoardBrainstormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board' | '/board/brainstorm'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/board/brainstorm'
  id: '__root__' | '/' | '/board' | '/board/brainstorm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/brainstorm': {
      id: '/board/brainstorm'
      path: '/brainstorm'
      fullPath: '/board/brainstorm'
      preLoaderRoute: typeof BoardBrainstormRouteImport
      parentRoute: typeof BoardRoute
    }
  }
}

interface BoardRouteChildren {
  BoardBrainstormRoute: typeof BoardBrainstormRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardBrainstormRoute: BoardBrainstormRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
