/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RandomRouteImport } from './routes/random'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardWhiteboardRouteImport } from './routes/board/whiteboard'
import { Route as BoardBrainstormRouteImport } from './routes/board/brainstorm'

const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardWhiteboardRoute = BoardWhiteboardRouteImport.update({
  id: '/whiteboard',
  path: '/whiteboard',
  getParentRoute: () => BoardRoute,
} as any)
const BoardBrainstormRoute = BoardBrainstormRouteImport.update({
  id: '/brainstorm',
  path: '/brainstorm',
  getParentRoute: () => BoardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/random': typeof RandomRoute
  '/board/brainstorm': typeof BoardBrainstormRoute
  '/board/whiteboard': typeof BoardWhiteboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/random': typeof RandomRoute
  '/board/brainstorm': typeof BoardBrainstormRoute
  '/board/whiteboard': typeof BoardWhiteboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRouteWithChildren
  '/random': typeof RandomRoute
  '/board/brainstorm': typeof BoardBrainstormRoute
  '/board/whiteboard': typeof BoardWhiteboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/random'
    | '/board/brainstorm'
    | '/board/whiteboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board' | '/random' | '/board/brainstorm' | '/board/whiteboard'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/random'
    | '/board/brainstorm'
    | '/board/whiteboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  RandomRoute: typeof RandomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/whiteboard': {
      id: '/board/whiteboard'
      path: '/whiteboard'
      fullPath: '/board/whiteboard'
      preLoaderRoute: typeof BoardWhiteboardRouteImport
      parentRoute: typeof BoardRoute
    }
    '/board/brainstorm': {
      id: '/board/brainstorm'
      path: '/brainstorm'
      fullPath: '/board/brainstorm'
      preLoaderRoute: typeof BoardBrainstormRouteImport
      parentRoute: typeof BoardRoute
    }
  }
}

interface BoardRouteChildren {
  BoardBrainstormRoute: typeof BoardBrainstormRoute
  BoardWhiteboardRoute: typeof BoardWhiteboardRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardBrainstormRoute: BoardBrainstormRoute,
  BoardWhiteboardRoute: BoardWhiteboardRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  RandomRoute: RandomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
