/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallbackGoogleRouteImport } from './routes/callback/google'
import { Route as CallbackGithubRouteImport } from './routes/callback/github'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackGoogleRoute = CallbackGoogleRouteImport.update({
  id: '/callback/google',
  path: '/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackGithubRoute = CallbackGithubRouteImport.update({
  id: '/callback/github',
  path: '/callback/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/callback/github': typeof CallbackGithubRoute
  '/callback/google': typeof CallbackGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/callback/github': typeof CallbackGithubRoute
  '/callback/google': typeof CallbackGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workspace': typeof WorkspaceRoute
  '/callback/github': typeof CallbackGithubRoute
  '/callback/google': typeof CallbackGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workspace' | '/callback/github' | '/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workspace' | '/callback/github' | '/callback/google'
  id: '__root__' | '/' | '/workspace' | '/callback/github' | '/callback/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRoute
  CallbackGithubRoute: typeof CallbackGithubRoute
  CallbackGoogleRoute: typeof CallbackGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/google': {
      id: '/callback/google'
      path: '/callback/google'
      fullPath: '/callback/google'
      preLoaderRoute: typeof CallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback/github': {
      id: '/callback/github'
      path: '/callback/github'
      fullPath: '/callback/github'
      preLoaderRoute: typeof CallbackGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRoute,
  CallbackGithubRoute: CallbackGithubRoute,
  CallbackGoogleRoute: CallbackGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
