/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CallbackGoogleImport } from './routes/callback/google'
import { Route as CallbackGithubImport } from './routes/callback/github'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CallbackGoogleRoute = CallbackGoogleImport.update({
  id: '/callback/google',
  path: '/callback/google',
  getParentRoute: () => rootRoute,
} as any)

const CallbackGithubRoute = CallbackGithubImport.update({
  id: '/callback/github',
  path: '/callback/github',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/callback/github': {
      id: '/callback/github'
      path: '/callback/github'
      fullPath: '/callback/github'
      preLoaderRoute: typeof CallbackGithubImport
      parentRoute: typeof rootRoute
    }
    '/callback/google': {
      id: '/callback/google'
      path: '/callback/google'
      fullPath: '/callback/google'
      preLoaderRoute: typeof CallbackGoogleImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callback/github': typeof CallbackGithubRoute
  '/callback/google': typeof CallbackGoogleRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback/github': typeof CallbackGithubRoute
  '/callback/google': typeof CallbackGoogleRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/callback/github': typeof CallbackGithubRoute
  '/callback/google': typeof CallbackGoogleRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/callback/github' | '/callback/google'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/callback/github' | '/callback/google'
  id: '__root__' | '/' | '/callback/github' | '/callback/google'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallbackGithubRoute: typeof CallbackGithubRoute
  CallbackGoogleRoute: typeof CallbackGoogleRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallbackGithubRoute: CallbackGithubRoute,
  CallbackGoogleRoute: CallbackGoogleRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/callback/github",
        "/callback/google"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/callback/github": {
      "filePath": "callback/github.tsx"
    },
    "/callback/google": {
      "filePath": "callback/google.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
